services:
  - type: web
    name: V-A-Y-U-Relay
    runtime: node
    rootDir: vayu-relay
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
